version: "2.7.14"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/1.sql"
    networks:
      ecommerce-net:

  ecommerce:
    container_name: ecommerce
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb
    networks:
      ecommerce-net:
    restart: on-failure

networks:
  ecommerce-net: