version: "2.7.14"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    networks:
      springboot-mysql-net:

  ecommerce:
    container_name: ecommerce
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.jpa.show-sql=true
      - spring.mvc.pathmatch.matching-strategy= ANT_PATH_MATCHER
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
    depends_on:
      - mysqldb
    networks:
      springboot-mysql-net:
    restart: on-failure

networks:
  springboot-mysql-net: